project:
  title: "Алгоритмы и структуры данных"
  type: website
  output-dir: ../docs/quarto
  # type: default # на делает слайдов с названиями секций
  resources:
    - resources/fonts
    - resources/images

format:
  beamer:
    keep-tex: true
    toc: true
    incremental: false
    pdf-engine: tectonic
    shift-heading-level-by: 0
    slide-level: 2
    slide-number: h.v
    linkcolor: red
    urlcolor: red
    center-title-slide: true
    number-sections: false
    mainfont: Cuprum
    monofont: Iosevka Term
    # classoption: "aspectratio=169"
    aspectratio: 169
    titlegraphic: resources/images/spbu-logo.pdf
    theme: Madrid
    # innertheme: default
    # outertheme: default
    colortheme: beaver
    # Но надо что-то делать c этим Section...
    section-titles: true
    template: resources/templates/beamer.template

  revealjs:
    # footer: "CS-103 Алгоритмы и структуры данных"
    shift-heading-level-by: 0
    slide-level: 2
    slide-number: h.v
    center-title-slide: true
    transition: slide
    progres: true
    touch: true
    # And more: https://quarto.org/docs/reference/formats/presentations/revealjs.html
    # theming:
    width: 100%
    height: 100%
    center: true
    min-scale: 0.5
    max-scale: 1
    theme: [ solarized, styles.scss ]
    include-in-header: 
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
